#! /usr/bin/env php
<?php
require 'vendor/autoload.php';

use \Symfony\Component\Console\Application;
use \Symfony\Component\Console\Input\InputInterface;
use \Symfony\Component\Console\Output\OutputInterface;
use \Symfony\Component\Console\Input\InputArgument;

$app = new Application('Doing Laracasts together', '1.0');

$app->add(new \Acme\SayHelloCommand());

$app->run();