#! /usr/bin/env php
<?php
require 'vendor/autoload.php';

use \Symfony\Component\Console\Application;
use \Symfony\Component\Console\Input\InputInterface;
use \Symfony\Component\Console\Output\OutputInterface;
use \Symfony\Component\Console\Input\InputArgument;

$app = new Application();

$app->register('sayHello')
    ->setDescription('Say hello to sombody')
    ->addArgument('name', InputArgument::OPTIONAL, 'Your name')
    ->setCode(function(InputInterface $input, OutputInterface $output){
        $name = $input->getArgument('name');
        $output->writeln('hello dear '. $name);
});

$app->run();